name: build

on:
  push:

env:
  ARTIFACTS_PATH: artifacts

jobs:
  Build:
    runs-on: [self-hosted, vm]
    if : ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Build Element
        env:
          PUSH_CFG: ${{ secrets.PUSH_CFG }}
        run: |
          set -eux

          mkdir -p ${ARTIFACTS_PATH}

          VERSION="$(exordos get-version .)"

          exordos build $(pwd)

          # Decode and write the push configuration
          echo "$PUSH_CFG" | base64 -d > exordos/exordos.push.yaml
          exordos push -c exordos/exordos.push.yaml -t local -f --latest
      - name: Setup upterm session
        uses: owenthereal/action-upterm@v1
        if: ${{ failure() }}
        with:
          limit-access-to-actor: true
          wait-timeout-minutes: 15
