name: build

on:
  push:
  workflow_dispatch:

env:
  PROJECT_NAME: genesis-notification
  REPO_ENDPOINT_PUT: http://10.20.0.1:8082

jobs:
  Build:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 30
      - name: Build Genesis Notification
        env:
              PUSH_CFG: ${{ secrets.PUSH_CFG }}
        run: |
          set -eux

          genesis build $(pwd) --inventory

          # Decode and write the push configuration
          echo "$PUSH_CFG" | base64 -d > genesis/genesis.push.yaml
          genesis push -c genesis/genesis.push.yaml -t local -f
